#
# Blog Settings
#
author: Sergey Maskalik
description: In the pursuit of mastery
url: https://blog.maskalik.com
title: Sergey Maskalik's blog
subscribe_rss: http://feeds.feedburner.com/sergeymaskaliksblog

# Github repositories
github_user: mercury2269
github_repo_url: https://github.com/mercury2269/mercury2269.github.io/

# Twitter
twitter_user: mercury2269
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: mercury2269
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-27808855-1

#
# Jekyll Settings
#
permalink: pretty
paginate: 3
paginate_path: "page/:num"
category_dir: categories

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from

prose:
  rooturl: "_posts"
  siteurl: "http://blog.maskalik.com"
  media: "uploads/2015"
  ignore:
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "meta description"
        field:
          element: "textarea"
          label: "Meta Description"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "estimation"
              value: "estimation"
            - name: "development practice"
              value: "development-practice"
            - name: "windows-service"
              value: "windows-service"
            - name: "message-queue"
              value: "message-queue"
            - name: "amazon-sqs"
              value: "amazon-sqs"
            - name: "business"
              value: "business"
            - name: "sales"
              value: "sales"
            - name: "database-migration"
              value: "database-migration"
            - name: "sql"
              value: "sql"
            - name: "continuous-delivery"
              value: "continuous-delivery"
            - name: "javascript"
              value: "javascript"
            - name: "learning"
              value: "learning"
            - name: "logstash"
              value: "logstash"
            - name: "book-recommendations"
              value: "book-recommendations"
            - name: "visual-studio-2013"
              value: "visual-studio-2013"
            - name: "msbuild"
              value: "msbuild"
            - name: "c#"
              value: "c#"
            - name: "entity-framework"
              value: "entity-framework"
            - name: "code-first"
              value: "code-first"
            - name: "detached-objects"
              value: "detached-objects"
            - name: "entrepreneur"
              value: "entrepreneur"
            - name: "book-review"
              value: "book-review"
            - name: "jekyll"
              value: "jekyll"
            - name: "cms"
              value: "cms"
            - name: "amazon-s3"
              value: "amazon-s3"
            - name: "tdd"
              value: "tdd"
            - name: "miniprofiler"
              value: "miniprofiler"
            - name: "powershell"
              value: "powershell"
            - name: "git"
              value: "git"
            - name: "spa"
              value: "spa"
            - name: "programming-concepts"
              value: "programming-concepts"
            - name: "programming"
              value: "programming"
            - name: "asp.net-mvc-4"
              value: "asp.net-mvc-4"
            - name: "asp.net"
              value: "asp.net"
            - name: "thread-safety"
              value: "thread-safety"
            - name: "asp.net-wcf"
              value: "asp.net-wcf"
            - name: "regex"
              value: "regex"
            - name: "better-programmer"
              value: "better-programmer"
            - name: "ado.net"
              value: "ado.net"
            - name: "sqldatareader"
              value: "sqldatareader"
            - name: "funnelweb"
              value: "funnelweb"
            - name: "spam"
              value: "spam"
            - name: "itunes"
              value: "itunes"
            - name: "dapper"
              value: "dapper"
            - name: "sqlite"
              value: "sqlite"
            - name: "heartbeat"
              value: "heartbeat"
            - name: "webmethod"
              value: "webmethod"
            - name: "ie9"
              value: "ie9"
            - name: "redirect"
              value: "redirect"
            - name: "browser-cache"
              value: "browser-cache"
            - name: "httpcookie"
              value: "httpcookie"
            - name: "webconfig"
              value: "webconfig"
            - name: "guides"
              value: "guides"
            - name: "service-broker"
              value: "service-broker"
            - name: "knockoutjs"
              value: "knockoutjs"
            - name: "sql-server-service-broker"
              value: "sql-server-service-broker"
            - name: "sql-server"
              value: "sql-server"
            - name: "external-activation"
              value: "external-activation"
            - name: "restsharp"
              value: "restsharp"
            - name: "oauth"
              value: "oauth"
            - name: "asynchronous"
              value: "asynchronous"
            - name: "trigger"
              value: "trigger"
            - name: "web-services"
              value: "web-services"
            - name: "thoughts"
              value: "thoughts"
            - name: "json.net"
              value: "json.net"
            - name: "serialization"
              value: "serialization"
            - name: "factual"
              value: "factual"
            - name: "factual-driver"
              value: "factual-driver"
            - name: "factual-asp-net-driver"
              value: "factual-asp-net-driver"
            - name: "cross-domain"
              value: "cross-domain"
            - name: "html5"
              value: "html5"
            - name: "authentication"
              value: "authentication"
            - name: "dom"
              value: "dom"
            - name: "favorites"
              value: "favorites"
            - name: "startup-weekend"
              value: "startup-weekend"
    _posts/pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
